### PR TITLE
Adds `make print` documentation in README

### PR DESCRIPTION
**Pull request by hayribakici**
See [Comment](https://github.com/idiv-biodiversity/pandoc-cheat-sheet/pull/4#issuecomment-2268478387) in #4 

@wookietreiber

### CODE REVIEW

**Review by wookietreiber — CHANGES_REQUESTED** [review]
Please leave the `Anytime you change ...` paragraph above the `Printer friendly version` header.

**Comment by wookietreiber** [comment]
Also, please rebase or cherry-pick on top of current master.

**Comment by hayribakici** [comment]
I thought the `Anytime you change...` sentence would apply to both `make` and `make print`, in which I therefore left it at the bottom.
I would rather add the `make print` to the sentence. What do you think?

**Comment by hayribakici** [comment]
closing, as force push made this PR obsolete. I'll create another PR

**Comment by wookietreiber** [comment]
> I thought the `Anytime you change...` sentence would apply to both `make` and `make print`, in which I therefore left it at the bottom. I would rather add the `make print` to the sentence. What do you think?

I guess I'd leave it as it was before and add a short note about that working with `make print` as well.

**Pull request closed without merging**
